- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
      force: true
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.gnupg/gpg.conf:
    ~/.shell:
    ~/.zsh:
    ~/.zshrc:
      force: true
    ~/.Brewfile:

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - git clean -fdx zsh/plugins/
  - brew bundle install
